from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class UserQuery(BaseModel):
    """Represents the question or request submitted by the user"""
    query_text: str = Field(..., min_length=1, max_length=2000, description="The text of the user's question or request")
    context: Optional[str] = Field(None, description="Additional context provided by the user")
    metadata: Optional[dict] = Field(None, description="Additional metadata for the query (e.g., user ID, session info)")

    class Config:
        json_schema_extra = {
            "example": {
                "query_text": "What is the main concept of RAG?",
                "context": "I'm learning about AI systems",
                "metadata": {"user_id": "12345"}
            }
        }


class RetrievedContext(BaseModel):
    """Represents the relevant text chunks retrieved from Qdrant based on similarity search"""
    id: str
    content: str = Field(..., min_length=1, description="The text content of the retrieved chunk")
    source_url: str = Field(..., description="URL or identifier of the original source")
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Score indicating how similar this chunk is to the query")
    metadata: dict = Field(default_factory=dict, description="Additional metadata from Qdrant (e.g., document title, section)")


class GeneratedAnswer(BaseModel):
    """Represents the response generated by the OpenAI Agent based on the user query and retrieved context"""
    id: str
    answer_text: str = Field(..., min_length=1, description="The text of the generated answer")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence level in the answer's accuracy")
    sources: List[str] = Field(default_factory=list, description="List of source URLs that contributed to the answer")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the answer was generated")
    query_id: str = Field(..., description="Reference to the original query")


class APIResponse(BaseModel):
    """Represents the structured response returned to the user containing the answer and metadata"""
    query_id: str = Field(..., description="Unique identifier for the query")
    answer: Optional[GeneratedAnswer] = Field(None, description="The generated answer object")
    retrieved_contexts: List[RetrievedContext] = Field(default_factory=list, description="List of contexts used to generate the answer")
    processing_time: float = Field(..., ge=0, description="Time taken to process the query in seconds")
    status: str = Field(..., description="Status of the request (success, partial, error)")
    error_message: Optional[str] = Field(None, description="Error message if the request failed")

    class Config:
        json_schema_extra = {
            "example": {
                "query_id": "query-123",
                "answer": {
                    "id": "answer-123",
                    "answer_text": "RAG stands for Retrieval-Augmented Generation...",
                    "confidence_score": 0.95,
                    "sources": ["https://example.com/doc1"],
                    "timestamp": "2023-12-18T10:00:00",
                    "query_id": "query-123"
                },
                "retrieved_contexts": [
                    {
                        "id": "context-123",
                        "content": "Retrieval-Augmented Generation combines...",
                        "source_url": "https://example.com/doc1",
                        "similarity_score": 0.85,
                        "metadata": {"title": "RAG Explained"}
                    }
                ],
                "processing_time": 1.23,
                "status": "success",
                "error_message": None
            }
        }